@startuml

title __LISTENER's Class Diagram__\n

  
    namespace Listener {
      interface Listener.ConsultationDrugsModelListener {
          {abstract} + onChangeModel()
      }
    }

  

  
    namespace Listener {
      interface Listener.ConsultationDrugsViewListener {
          {abstract} + onSearch()
      }
    }

  

  
    namespace Listener {
      interface Listener.ConsultationPratitionnerViewListener {
          {abstract} + onSearch()
      }
    }

  

  
    namespace Listener {
      interface Listener.ConsultationRapportVisiteModelListener {
          {abstract} + onRapportVisiteChange()
      }
    }

  

  
    namespace Listener {
      interface Listener.ConsultationRapportVisitesListener {
          {abstract} + onSearchSubmit()
      }
    }

  

  
    namespace Listener {
      interface Listener.ConsultationRapportVisitesModelListener {
          {abstract} + onRapportVisitesChange()
      }
    }

  

  
    namespace Listener {
      interface Listener.ContextListener {
          {abstract} + userLoginSucess()
      }
    }

  

  
    namespace Listener {
      interface Listener.LoginListener {
          {abstract} + onSubmit()
      }
    }

  

  
    namespace Listener {
      interface Listener.MenuListener {
          {abstract} + onConsulterClicked()
          {abstract} + onDrugsClicked()
          {abstract} + onNewReportClicked()
          {abstract} + onPratitionnersClicked()
      }
    }

  

  
    namespace Listener {
      interface Listener.NewReportListener {
          {abstract} + onSubmitNewReport()
      }
    }

  

  
    namespace Listener {
      interface Listener.RouteListener {
          {abstract} + onDrugConsultation()
          {abstract} + onError()
          {abstract} + onNewReport()
          {abstract} + onPratitionners()
          {abstract} + onReportConsultation()
          {abstract} + onReportConsultations()
      }
    }

  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
